openapi: 3.0.0
info:
  title: API-008
  version: '1.0'
  description: 別納一括入力用API
servers:
  - url: 'http://localhost:3000/shipment-control'
paths:
  /v1/arranged-shipment/upload:
    parameters: []
    post:
      summary: 別納_一括アップロードAPI
      tags:
        - ArrangedShipment
      operationId: uploadArrangedShipmentV1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: 更新成否結果リスト
                items:
                  $ref: '#/components/schemas/UploadArrangedShipmentResponseV1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      description: 別納一括登録ファイルをアップロードし、アップロード結果ファイルを生成する。
      x-channel:
        - office
        - supplier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadArrangedShipmentRequestV1'
      parameters:
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Idempotency-Key
components:
  schemas:
    UploadArrangedShipmentRequestV1:
      title: UploadArrangedShipmentRequestV1
      type: object
      properties:
        subsidiaryCode:
          type: string
          maxLength: 3
          description: 現法コード
        processTypeCode:
          type: string
          maxLength: 1
          description: 処理区分コード
        fileName:
          type: string
          description: ファイル名
          maxLength: 432
        tempFileId:
          type: string
          description: 一時ファイルID
          maxLength: 256
        fileSign:
          type: string
          description: 署名
          maxLength: 256
        updateId:
          type: string
          maxLength: 6
          description: 更新者ID
        updateTime:
          type: string
          format: date-time
          minLength: 14
          maxLength: 14
          description: 更新日時
        updateProgram:
          type: string
          description: 更新プログラム
          maxLength: 15
      required:
        - subsidiaryCode
        - fileName
        - tempFileId
        - fileSign
        - updateId
        - updateTime
        - updateProgram
    UploadArrangedShipmentResponseV1:
      title: UploadArrangedShipmentResponseV1
      type: object
      properties:
        updateResult:
          type: string
          description: 更新成否結果
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
      required:
        - updateResult
  parameters: {}
tags:
  - name: ArrangedShipment
