openapi: 3.0.0
info:
  title: API-012
  version: '1.0'
  description: 在庫調整一括入力用API
servers:
  - url: 'http://localhost:3000/shipment-control'
paths:
  /v1/stock-adjustment/upload:
    post:
      summary: 在庫調整_在庫調整一括アップロードAPI
      operationId: uploadStockAdjustmentV1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: 伝票リスト
                items:
                  $ref: '#/components/schemas/UploadStockAdjustResponseV1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      description: 在庫調整一括ファイルをアップロードし、アップロード結果ファイルを生成する。
      x-channel:
        - office
        - supplier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadStockAdjustRequestV1'
      parameters:
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Idempotency-Key
      tags:
        - StockAdjustment
    parameters: []
components:
  schemas:
    UploadStockAdjustResponseV1:
      title: UploadStockAdjustResponseV1
      type: object
      properties:
        receptionResult:
          type: string
          description: 受付成否結果
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
      required:
        - receptionResult
    UploadStockAdjustRequestV1:
      title: UploadStockAdjustRequestV1
      type: object
      properties:
        subsidiaryCode:
          type: string
          maxLength: 3
          description: 現法コード
        fileName:
          type: string
          description: ファイル名
          maxLength: 432
        id:
          type: string
          description: ID
        tempFileId:
          type: string
          description: 一時ファイルID
          maxLength: 256
        fileSign:
          type: string
          description: 署名
          maxLength: 256
        updateId:
          type: string
          maxLength: 6
          description: 更新者ID
        updateTime:
          type: string
          description: 更新日時
          format: date-time
          maxLength: 14
          minLength: 14
        updateProgram:
          type: string
          maxLength: 15
          description: 更新プログラム
      required:
        - subsidiaryCode
        - fileName
        - id
        - tempFileId
        - fileSign
        - updateId
        - updateTime
        - updateProgram
  parameters: {}
tags:
  - name: StockAdjustment
