openapi: 3.0.0
info:
  title: API-021
  version: '1.0'
  description: 当日着荷緊急締め用API
servers:
  - url: 'http://localhost:3000/shipment-control'
paths:
  /v1/vstork-delivery/search:
    get:
      summary: 出荷_当日着荷参照API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchVstorkDeliveryResponseV1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      operationId: searchVstorkDeliveryV1
      description: 当日着荷(Vストーク)緊急締め、置場マスタの登録内容を参照する。
      x-channel:
        - office
        - supplier
      parameters:
        - schema:
            type: string
            maxLength: 3
          in: query
          name: subsidiaryCode
          required: true
          description: 現法コード
        - schema:
            type: string
            maxLength: 4
          in: query
          name: plantCode
          description: 置場コード
        - schema:
            type: string
            maxLength: 1
          in: query
          name: deliveryServiceStatus
          description: 即納配送状態
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortby'
      tags:
        - VstorkDelivery
    parameters: []
  /v1/vstork-delivery/save:
    post:
      summary: 出荷_当日着荷更新API
      operationId: saveVstorkDeliveryV1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: 更新可否結果リスト
                items:
                  $ref: '#/components/schemas/SaveVstorkDeliveryResponseV1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      description: 当日着荷(Vｽﾄｰｸ)緊急締めを更新する。
      x-channel:
        - office
        - supplier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveVstorkDeliveryRequestV1'
      parameters:
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Idempotency-Key
      tags:
        - VstorkDelivery
    parameters: []
components:
  schemas:
    SearchVstorkDeliveryResponseV1:
      title: SearchVstorkDeliveryResponseV1
      type: object
      properties:
        subsidiaryCode:
          type: string
          description: 現法コード
          maxLength: 3
        resultCount:
          type: integer
          description: 取得件数
        infoList:
          type: array
          description: 情報一覧リスト
          items:
            $ref: '#/components/schemas/SearchVstorkDeliveryInfoListV1'
      required:
        - resultCount
    SearchVstorkDeliveryInfoListV1:
      title: SearchVstorkDeliveryInfoListV1
      type: object
      description: 情報一覧リスト
      properties:
        plantCode:
          type: string
          description: 置場コード
          maxLength: 4
        plantName:
          type: string
          description: 置場名
          maxLength: 45
        deliveryServiceStatus:
          type: string
          description: 即納配送状態
          maxLength: 1
        updateDate:
          type: string
          description: 更新日
          format: date
        updateId:
          type: string
          description: 更新者ID
          maxLength: 256
        updateCount:
          type: integer
          description: 更新回数
          maximum: 9999
    SaveVstorkDeliveryRequestV1:
      title: SaveVstorkDeliveryRequestV1
      type: object
      properties:
        subsidiaryCode:
          type: string
          description: 現法コード
          maxLength: 3
        updateId:
          type: string
          description: 更新者ID
          maxLength: 6
        updateTime:
          type: string
          description: 更新日時
          maxLength: 14
          format: date-time
          minLength: 14
        updateProgram:
          type: string
          description: 更新プログラム
          maxLength: 15
        informationList:
          type: array
          items:
            $ref: '#/components/schemas/SaveVstorkDeliveryInfoListV1'
      required:
        - subsidiaryCode
        - updateId
        - updateTime
        - updateProgram
        - informationList
    SaveVstorkDeliveryInfoListV1:
      title: SaveVstorkDeliveryInfoListV1
      type: object
      properties:
        plantCode:
          type: string
          maxLength: 4
          description: 置場コード
        deliveryServiceStatus:
          type: string
          description: 即納配送状態
          maxLength: 1
        updateCount:
          type: integer
          description: 更新回数
          maximum: 9999
      required:
        - plantCode
        - deliveryServiceStatus
        - updateCount
    SaveVstorkDeliveryResponseV1:
      title: SaveVstorkDeliveryResponseV1
      type: object
      properties:
        plantCode:
          type: string
          description: 置場コード
          maxLength: 4
        updateResult:
          type: string
          description: 更新結果
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
      required:
        - plantCode
        - updateResult
  parameters:
    offset:
      name: offset
      in: query
      required: true
      schema:
        type: integer
      description: 取得開始位置
    limit:
      name: limit
      in: query
      required: true
      schema:
        type: integer
      description: 返却件数
    sortby:
      name: sortby
      in: query
      required: true
      schema:
        type: string
      description: ソート順1
  securitySchemes: {}
tags:
  - name: VstorkDelivery
