openapi: 3.0.0
info:
  title: API-014
  version: '1.0'
  description: 出荷不可照会用API
servers:
  - url: 'http://localhost:3000/shipment-control'
paths:
  /internal/v1/stop-shipment/print:
    post:
      summary: 出荷不可_印刷API
      operationId: printStopShipmentInternalV1
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrintStopShipmentInternalResponseV1'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
        '409':
          description: Conflict
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PrintStopShipmentInternalRequestV1'
        description: ''
      description: 出荷不可連絡リストを作成し、帳票を出力する。出荷不可連絡リストにメール送信し、出荷不可連絡リストテーブルに反映する。
      x-channel:
        - internal
      parameters:
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Idempotency-Key
      tags:
        - StopShipmentInternal
    parameters: []
  /internal/v1/stop-shipment/search:
    post:
      summary: 出荷不可_参照API
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/SearchStopShipmentInternalResponseV1'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      operationId: searchStopShipmentInternalV1
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/SearchStopShipmentInternalRequestV1'
        description: ''
      description: 出荷不可データの出荷不可情報、受注明細情報、社内移動情報、各種マスタ情報を参照する
      x-channel:
        - internal
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortby'
        - $ref: '#/components/parameters/sortby2'
      tags:
        - StopShipmentInternal
    parameters: []
components:
  schemas:
    PrintStopShipmentInternalPrintListV1:
      title: PrintStopShipmentInternalPrintListV1
      type: object
      properties:
        globalNumber:
          type: string
          description: グローバル番号
          maxLength: 14
        productCode:
          type: string
          description: 商品コード
          maxLength: 234
        brandCode:
          type: string
          description: ブランドコード
          maxLength: 4
        contactList:
          type: string
          description: 連絡リスト
          maxLength: 1
        quantity:
          type: integer
          description: 数量
          maximum: 9999999
        supplierName:
          type: string
          description: 仕入先名
          maxLength: 200
        marketCode:
          type: string
          description: 市場
          maxLength: 2
        plantCode:
          type: string
          description: 置場
          maxLength: 4
        storageLocationCode:
          type: string
          description: 保管場所
          maxLength: 4
        voucherType:
          type: string
          description: 伝区
          maxLength: 3
        soArrivalDate:
          type: string
          description: 受注入荷日
          format: date-time
        soShipmentDate:
          type: string
          description: 受注出荷日
          format: date-time
        soStatus:
          type: string
          description: 受注状態
          maxLength: 1
        stopShipmentFlag:
          type: string
          description: 出荷不可フラグ
          maxLength: 1
        inputProcessDate:
          type: string
          description: 入力日付
          format: date
        time:
          type: string
          description: 時刻
          format: time
        id:
          type: string
          description: ID
        historyDisDiv:
          type: string
          description: 履歴表示区分
          maxLength: 1
        updateCount:
          type: integer
          description: 更新回数
          maximum: 9999
      required:
        - globalNumber
        - productCode
        - brandCode
        - quantity
        - supplierName
        - marketCode
        - plantCode
        - storageLocationCode
        - voucherType
        - soArrivalDate
        - soShipmentDate
        - soStatus
        - stopShipmentFlag
        - inputProcessDate
        - time
        - id
        - updateCount
    SearchStopShipmentInternalRequestV1:
      title: SearchStopShipmentInternalRequestV1
      type: object
      properties:
        supplierCode:
          type: string
          description: 仕入先コード
          maxLength: 4
        globalNumber:
          type: string
          description: グローバル番号
          maxLength: 14
        customerCode:
          type: string
          description: 得意先コード
          maxLength: 6
        supplierInvNo:
          type: string
          description: SupplierI/V No
          maxLength: 25
        registerUserId:
          type: string
          description: 登録者ＩＤ
          maxLength: 256
        plantCode:
          type: string
          description: 置場
          maxLength: 4
        stopShipmentArrivalDateFrom:
          type: string
          description: 出荷不可入荷日(FROM)
          format: date-time
        stopShipmentArrivalDateTo:
          type: string
          description: 出荷不可入荷日（TO)
          format: date-time
        stopShipmentShipmentDateFrom:
          type: string
          description: 出荷不可出荷日(FROM)
          format: date-time
        stopShipmentShipmentDateTo:
          type: string
          description: 出荷不可出荷日(TO)
          format: date-time
        historyDisDiv:
          type: string
          description: 履歴表示区分
          maxLength: 1
        voucherType:
          type: string
          description: 伝区
          maxLength: 3
        sendSlipType:
          type: string
          description: 伝票送付区分
          maxLength: 1
        marketCode:
          type: string
          description: 市場
          maxLength: 2
        soStatus:
          type: string
          description: 受注状態
          maxLength: 1
        stopShipmentFlag:
          type: string
          description: 出荷不可フラグ
          maxLength: 1
        contactList:
          type: string
          description: 連絡リスト
          maxLength: 1
        inquiryTarget:
          type: string
          description: 照会対象
          maxLength: 1
        stockType:
          type: string
          description: 在庫区分
          maxLength: 1
        storkCode:
          type: string
          description: ストークコード
          maxLength: 2
        shipmentMeansCode:
          type: string
          description: 出荷方法コード
          maxLength: 4
        maxCount:
          description: 参照最大件数
          type: integer
      required:
        - plantCode
        - stopShipmentArrivalDateFrom
        - stopShipmentShipmentDateFrom
        - maxCount
    SearchStopShipmentInternalResponseV1:
      title: SearchStopShipmentInternalResponseV1
      type: object
      properties:
        count:
          type: integer
          description: 件数
        stopShipmentList:
          type: array
          description: 出荷不可リスト
          items:
            $ref: '#/components/schemas/SearchStopShipmentInternalStopShipListV1'
      required:
        - count
    SearchStopShipmentInternalStopShipListV1:
      title: SearchStopShipmentInternalStopShipListV1
      type: object
      description: 出荷不可リスト
      properties:
        globalNumber:
          type: string
          description: グローバル番号
          maxLength: 14
        productCode:
          type: string
          description: 商品コード
          maxLength: 234
        brandCode:
          type: string
          description: ブランドコード
          maxLength: 4
        nativeBrandName:
          type: string
          description: ブランド名称(現地語)
          maxLength: 200
        brandName:
          type: string
          description: ブランド名称(英語)
          maxLength: 15
        contactList:
          type: string
          description: 連絡リスト
          maxLength: 1
        contactListName:
          type: string
          description: 連絡リスト名
          maxLength: 1
        quantity:
          type: integer
          description: 数量
          maximum: 9999999
        supplierCode:
          type: string
          description: 仕入先
          maxLength: 4
        supplierName:
          type: string
          description: 仕入先名
          maxLength: 200
        marketCode:
          type: string
          description: 市場
          maxLength: 2
        marketName:
          type: string
          description: 市場名
        plantCode:
          type: string
          description: 置場
          maxLength: 4
        plantName:
          type: string
          description: 置場名
          maxLength: 45
        storageLocationCode:
          type: string
          description: 保管場所
          maxLength: 4
        storageLocationName:
          type: string
          description: 保管場所名
          maxLength: 45
        supplyMeansType:
          type: string
          description: 調達方法区分
          maxLength: 2
        supplyMeansTypeName:
          type: string
          description: 調達方法区分名
        voucherType:
          type: string
          description: 伝区
          maxLength: 3
        voucherTypeName:
          type: string
          description: 伝票区分名
        sendSlipType:
          type: string
          description: 伝票送付区分
          maxLength: 1
        sendSlipTypeName:
          type: string
          description: 伝票送付区分名
        soArrivalDate:
          type: string
          description: 受注入荷日
          format: date-time
        soShipmentDate:
          type: string
          description: 受注出荷日
          format: date-time
        soStatus:
          type: string
          description: 受注状態
          maxLength: 1
        soStatusName:
          type: string
          description: 受注状態名
        stopShipmentFlag:
          type: string
          description: 出荷不可フラグ
          maxLength: 1
        stopShipmentFlagName:
          type: string
          description: 出荷不可フラグ名
        inputProcessDate:
          type: string
          description: 入力日付
          format: date
        time:
          type: string
          description: 時刻
          format: time
        id:
          type: string
          description: ＩＤ(更新者IDを指す)
        updateCount:
          type: integer
          description: 更新回数
          maximum: 9999
        errorList:
          type: array
          description: エラーリスト
          items:
            $ref: '#/components/schemas/SearchStopShipmentInternalErrorListV1'
      required:
        - globalNumber
        - productCode
        - brandCode
        - nativeBrandName
        - brandName
        - contactList
        - contactListName
        - quantity
        - supplierCode
        - supplierName
        - marketCode
        - marketName
        - plantCode
        - plantName
        - storageLocationCode
        - storageLocationName
        - supplyMeansType
        - supplyMeansTypeName
        - voucherType
        - voucherTypeName
        - sendSlipType
        - sendSlipTypeName
        - soArrivalDate
        - soShipmentDate
        - soStatus
        - soStatusName
        - stopShipmentFlag
        - stopShipmentFlagName
        - inputProcessDate
        - time
        - id
        - updateCount
    PrintStopShipmentInternalResponseV1:
      title: PrintStopShipmentInternalResponseV1
      type: object
      description: 処理結果情報リスト
      properties:
        resultInformation:
          type: string
          description: 処理結果情報
        errorList:
          description: エラーリスト
          type: array
          items:
            $ref: '#/components/schemas/PrintStopShipmentInternalErrorListV1'
      required:
        - resultInformation
    PrintStopShipmentInternalRequestV1:
      title: PrintStopShipmentInternalRequestV1
      type: object
      properties:
        updateTime:
          type: string
          description: 更新日時
          maxLength: 14
          format: date-time
          minLength: 14
        businessSceneType:
          type: string
          description: 業務シーン区分
          maxLength: 2
        printList:
          type: array
          items:
            $ref: '#/components/schemas/PrintStopShipmentInternalPrintListV1'
      required:
        - updateTime
        - businessSceneType
    SearchStopShipmentInternalErrorListV1:
      title: SearchStopShipmentInternalErrorListV1
      type: object
      properties:
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
    PrintStopShipmentInternalErrorListV1:
      title: PrintStopShipmentInternalErrorListV1
      type: object
      properties:
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
  parameters:
    offset:
      name: offset
      in: query
      required: true
      schema:
        type: integer
      description: 取得開始位置
    limit:
      name: limit
      in: query
      required: true
      schema:
        type: integer
      description: 返却件数
    sortby:
      name: sortby
      in: query
      schema:
        type: string
      description: ソート順1
    sortby2:
      name: sortby2
      in: query
      required: true
      schema:
        type: string
      description: ソート順2
tags:
  - name: StopShipmentInternal
