openapi: 3.0.0
info:
  title: API-000
  version: '1.0'
  description: 別納参照用API
servers:
  - url: 'http://localhost:3000/shipment-control'
paths:
  /v1/arranged-shipment/search:
    post:
      summary: 別納参照API
      tags:
        - ArrangedShipment
      operationId: searchArrangedShipment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchArrangedShipmentResponseV1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      description: 別納の登録内容を参照する。
      x-channel:
        - office
        - supplier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchArrangedShipmentRequestV1'
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
    parameters: []
components:
  schemas:
    SearchArrangedShipmentRequestV1:
      title: SearchArrangedShipmentRequestV1
      type: object
      properties:
        subsidiaryCode:
          type: string
          maxLength: 3
          description: 現法コード
        inputInfoList:
          type: array
          items:
            $ref: '#/components/schemas/SearchArrangedShipmentInfoListV1'
        sortList:
          type: array
          items:
            $ref: '#/components/schemas/SearchArrangedShipmentSortListV1'
      required:
        - subsidiaryCode
    SearchArrangedShipmentInfoListV1:
      title: SearchArrangedShipmentInfoListV1
      type: object
      description: 別納参照APIリクエスト項目
      properties:
        globalNumber:
          type: string
          description: グローバル番号
          maxLength: 14
        inputProcessDate:
          type: string
          format: date-time
          description: 入力日付
      required:
        - globalNumber
        - inputProcessDate
    SearchArrangedShipmentSortListV1:
      title: SearchArrangedShipmentSortListV1
      type: object
      properties:
        sortCondition:
          type: string
          description: ソート条件
      required:
        - sortCondition
    SearchArrangedShipmentResponseV1:
      title: SearchArrangedShipmentResponseV1
      type: object
      properties:
        subsidiaryCode:
          type: string
          description: 現法コード
          maxLength: 3
        resultCount:
          type: integer
          description: 取得件数
        arrnInformationList:
          type: array
          description: 別納情報リスト
          items:
            $ref: '#/components/schemas/SearchArrangedShipmentResInfoListV1'
      required:
        - subsidiaryCode
        - resultCount
    SearchArrangedShipmentResInfoListV1:
      title: SearchArrangedShipmentResInfoListV1
      type: object
      x-examples: {}
      description: 別納情報リスト
      properties:
        globalNumber:
          type: string
          description: グローバル番号
          maxLength: 14
        inputProcessDate:
          type: string
          format: date-time
          description: 入力日付
        customerCode:
          type: string
          description: 得意先コード
          maxLength: 6
        productCode:
          type: string
          description: 商品コード
          maxLength: 234
        gInnerCode:
          type: string
          description: 統合インナーコード
          maxLength: 14
        soQty:
          type: integer
          description: 受注数量
          maximum: 9999999
          minimum: 0
        totalShipQty:
          type: integer
          description: 出荷累計数
          maximum: 9999999
          minimum: 0
        estShipQty:
          type: integer
          description: 出荷予定数
          maximum: 9999999
          minimum: 0
        arrnShipQty:
          type: integer
          description: 別納出荷数
          maximum: 9999999
          minimum: 0
        supplierCode:
          type: string
          description: 仕入先コード
          maxLength: 4
        supplierSection:
          type: integer
          description: 担当課
          minimum: 0
          maximum: 99
        reasonCode:
          type: string
          description: 理由コード
          maxLength: 5
        outputFlag:
          type: string
          description: 出力フラグ
          maxLength: 1
        soDate:
          type: string
          description: 受注日
          format: date-time
        vsd:
          type: string
          description: VSD
          format: date-time
        shipToCd:
          type: string
          description: 直送先コード
          maxLength: 6
        analysisCode:
          type: string
          description: 分析コード
          maxLength: 8
        marketCode:
          type: string
          description: 市場コード
          maxLength: 2
        largeClassification:
          type: string
          description: 大分類
          maxLength: 2
        productControlDepartmentCode:
          type: string
          description: 商品所管部門コード
          maxLength: 6
        plantCodeOld:
          type: string
          description: 置場コード（変更前）
          maxLength: 4
        storageLocationCodeOld:
          type: string
          description: 保管場所コード（変更前）
          maxLength: 4
        plantCodeNew:
          type: string
          description: 置場コード（変更後）
          maxLength: 4
        storageLocationCodeNew:
          type: string
          description: 保管場所コード（変更後）
          maxLength: 4
        statusFlag:
          type: string
          description: 別納状況フラグ
          maxLength: 1
        cometFlag:
          type: string
          description: COMET送信管理フラグ
          maxLength: 1
        arrnShipDiv:
          type: string
          description: 別納区分
          maxLength: 1
        orderAttributes:
          type: string
          description: 注文属性
          maxLength: 2
        voucherType:
          type: string
          description: 伝票区分
          maxLength: 3
        sendSlip:
          type: string
          description: 伝票送付
          maxLength: 1
        brandCode:
          type: string
          description: ブランドコード
          maxLength: 4
        supplierGroupCode:
          type: string
          description: POCグループ１
          maxLength: 4
        updateCount:
          type: integer
          description: 更新回数
          minimum: 0
          maximum: 9999
        deleteFlag:
          type: string
          description: 削除フラグ
          maxLength: 1
        registerUser:
          type: string
          description: 登録者
          maxLength: 256
        registerTime:
          type: string
          description: 登録日時
          format: date-time
        updateName:
          type: string
          description: 更新者
          maxLength: 256
        updateTime:
          type: string
          description: 更新日時
          format: date-time
  parameters:
    offset:
      name: offset
      in: query
      required: true
      schema:
        type: integer
      description: 取得開始位置
    limit:
      name: limit
      in: query
      required: true
      schema:
        type: integer
      description: 返却件数
tags:
  - name: ArrangedShipment
