openapi: 3.0.0
info:
  title: API-015
  version: '1.0'
  description: 出荷不可一括入力用API
servers:
  - url: 'http://localhost:3000/shipment-control'
paths:
  /internal/v1/stop-shipment/upload:
    post:
      summary: 出荷不可_一括アップロードAPI
      operationId: uploadStopShipmentInternalV1
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/UploadStopShipmentInternalResponseV1'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
        '409':
          description: Conflict
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/UploadStopShipmentInternalRequestV1'
        description: ''
      description: 出荷不可一括ファイルをアップロードすることで出荷不可データを更新・登録し、アップロード結果ファイルを生成する。
      x-channel:
        - internal
      parameters:
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Idempotency-Key
      tags:
        - StopShipmentInternal
    parameters: []
  /internal/v1/stop-shipment/download:
    post:
      summary: 出荷不可_一括ダウンロードAPI
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/DownloadStopShipmentInternalResponseV1'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      operationId: downloadStopShipmentInternalV1
      description: 出荷不可データを取得し、出荷不可DLファイルを生成する。
      x-channel:
        - internal
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/DownloadStopShipmentInternalRequestV1'
      tags:
        - StopShipmentInternal
    parameters: []
  /internal/v1/stop-shipment/bulk-search:
    post:
      summary: 出荷不可_一括参照API
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/BulkSearchStopShipmentInternalResponseV1'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
      operationId: bulkSearchStopShipmentInternalV1
      description: 出荷不可データの出荷不可情報、発注情報、受注情報、社内移動情報、各種マスタ情報を参照する。
      x-channel:
        - internal
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BulkSearchStopShipmentInternalRequestV1'
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortby'
        - $ref: '#/components/parameters/sortby2'
      tags:
        - StopShipmentInternal
    parameters: []
components:
  schemas:
    UploadStopShipmentInternalRequestV1:
      title: UploadStopShipmentInternalRequestV1
      type: object
      properties:
        fileName:
          type: string
          description: ファイル名
          maxLength: 432
        tempFileId:
          type: string
          description: 一時ファイルID
          maxLength: 256
        fileSign:
          type: string
          description: 署名
          maxLength: 256
        updateTime:
          type: string
          description: 更新日時
          format: date-time
          minLength: 14
          maxLength: 14
      required:
        - fileName
        - tempFileId
        - fileSign
        - updateTime
    BulkSearchStopShipmentInternalRequestV1:
      title: BulkSearchStopShipmentInternalRequestV1
      type: object
      properties:
        businessSceneType:
          type: string
          description: 業務シーン区分
          maxLength: 2
        plantCode:
          type: string
          description: 置場コード
          maxLength: 4
        supplierCode:
          type: string
          description: 仕入先コード
          maxLength: 4
        stopShipmentArrivalDateFrom:
          type: string
          description: 出荷不可入荷日(FROM)
          format: date-time
          maxLength: 8
        stopShipmentArrivalDateTo:
          type: string
          description: 出荷不可入荷日(TO)
          format: date-time
          maxLength: 8
        globalNumber:
          type: string
          description: グローバル番号
          maxLength: 14
        stopShipmentDateFrom:
          type: string
          description: 出荷不可出荷日(From)
          format: date-time
          maxLength: 8
        stopShipmentDateTo:
          type: string
          description: 出荷不可出荷日(To)
          format: date-time
          maxLength: 8
        customerCode:
          type: string
          description: 得意先コード
          maxLength: 6
        voucherType:
          type: string
          description: 伝区コード
          maxLength: 3
        sendSlipType:
          type: string
          description: 伝票送付区分
          maxLength: 1
        stopShipmentFlag:
          type: string
          description: 出荷不可フラグ
          maxLength: 1
        supplierInvNo:
          type: string
          description: Supplier I/V No
          maxLength: 25
        marketCode:
          type: string
          description: 市場コード
          maxLength: 2
        contactList:
          type: string
          description: 連絡リスト
          maxLength: 1
        registerUserId:
          type: string
          description: 登録者ID
          maxLength: 256
        soStatus:
          type: string
          description: 受注状態区分
          maxLength: 1
        inquiryTarget:
          type: string
          description: 照会対象区分
          maxLength: 1
        storkCode:
          type: string
          description: ストークコード
          maxLength: 2
        shipmentMeansCode:
          type: string
          description: 出荷方法コード
          maxLength: 4
        stockType:
          type: string
          description: 在庫区分
          maxLength: 1
        maxCount:
          description: 参照最大件数
          type: integer
      required:
        - businessSceneType
        - stopShipmentArrivalDateFrom
        - stopShipmentDateFrom
    BulkSearchStopShipmentInternalResponseV1:
      title: BulkSearchStopShipmentInternalResponseV1
      type: object
      description: ''
      properties:
        count:
          description: 件数
          type: integer
        stopShipmentAllList:
          description: 出荷不可一括リスト
          type: array
          items:
            $ref: '#/components/schemas/BulkSearchStopShipmentInternalListV1'
      required:
        - count
    BulkSearchStopShipmentInternalListV1:
      title: BulkSearchStopShipmentInternalListV1
      type: object
      properties:
        globalNumber:
          type: string
          description: グローバル番号
          maxLength: 14
        productCode:
          type: string
          description: 商品コード
          maxLength: 234
        brandCode:
          type: string
          description: ブランド
          maxLength: 4
        nativeBrandName:
          type: string
          description: ブランド名称(現地語)
          maxLength: 200
        brandName:
          type: string
          description: ブランド名称(英語)
          maxLength: 15
        contactList:
          type: string
          description: 連絡リスト
          maxLength: 1
        contactListName:
          type: string
          description: 連絡リスト名
        quantity:
          type: integer
          description: 数量
          maximum: 9999999
        supplierCode:
          type: string
          description: 仕入先
          maxLength: 4
        supplierName:
          type: string
          description: 仕入先名
          maxLength: 200
        marketCode:
          type: string
          description: 市場
          maxLength: 2
        marketName:
          type: string
          description: 市場名
        plantCode:
          type: string
          description: 置場
          maxLength: 4
        plantName:
          type: string
          description: 置場名
          maxLength: 45
        supplyMeansType:
          type: string
          description: 調達方法区分
          maxLength: 2
        supplyMeansTypeName:
          type: string
          description: 調達方法区分名
        storageLocationCode:
          type: string
          description: 保管場所
          maxLength: 4
        storageLocationName:
          type: string
          description: 保管場所名
          maxLength: 45
        voucherType:
          type: string
          description: 伝区
          maxLength: 3
        voucherTypeName:
          type: string
          description: 伝区名
        sendSlipType:
          type: string
          description: 伝票送付区分
          maxLength: 1
        sendSlipTypeName:
          type: string
          description: 伝票送付区分名
        soArrivalDate:
          type: string
          description: 受注入荷日
          format: date-time
        soShipmentDate:
          type: string
          description: 受注出荷日
          format: date-time
        updateTime:
          type: string
          description: 更新時刻
          format: time
        id:
          type: string
          description: ID(更新者IDを指す)
        soStatus:
          type: string
          description: 受注状態
          maxLength: 1
        soStatusName:
          type: string
          description: 受注状態名
        stopShipmentFlg:
          type: string
          description: 出荷不可フラグ
        stopShipmentFlgName:
          type: string
          description: 出荷不可フラグ名
        reasonType:
          type: string
          description: 理由区分
          maxLength: 5
        reasonTypeName:
          type: string
          description: 理由区分名
          maxLength: 40
        getDataType:
          type: string
          description: 取得元データ区分
          maxLength: 1
        updateCount:
          type: integer
          maximum: 9999
          description: 更新回数
        errorList:
          type: array
          description: エラーリスト
          items:
            $ref: '#/components/schemas/BulkSearchStopShipmentInternalErrorListV1'
      required:
        - globalNumber
        - productCode
        - brandCode
        - nativeBrandName
        - brandName
        - contactList
        - contactListName
        - quantity
        - supplierCode
        - supplierName
        - marketCode
        - marketName
        - plantCode
        - plantName
        - supplyMeansType
        - supplyMeansTypeName
        - storageLocationCode
        - storageLocationName
        - voucherType
        - voucherTypeName
        - sendSlipType
        - sendSlipTypeName
        - soArrivalDate
        - soShipmentDate
        - updateTime
        - id
        - soStatus
        - soStatusName
        - stopShipmentFlg
        - stopShipmentFlgName
        - reasonType
        - reasonTypeName
        - getDataType
        - updateCount
    UploadStopShipmentInternalResponseV1:
      title: UploadStopShipmentInternalResponseV1
      type: object
      properties:
        receptionResult:
          type: string
          description: 受付可否結果
          maxLength: 1
        updateResultList:
          type: array
          description: 更新成否結果リスト
          items:
            $ref: '#/components/schemas/UploadStopShipmentInternalUpdateResultListV1'
      required:
        - receptionResult
    UploadStopShipmentInternalUpdateResultListV1:
      title: UploadStopShipmentInternalUpdateResultListV1
      type: object
      description: 更新成否結果リスト
      properties:
        updateResult:
          type: string
          description: 更新成否結果
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
      required:
        - updateResult
    DownloadStopShipmentInternalRequestV1:
      title: DownloadStopShipmentInternalRequestV1
      type: object
      properties:
        plantCode:
          type: string
          description: 置場コード
          maxLength: 4
        supplierCode:
          type: string
          description: 仕入先コード
          maxLength: 4
        stopShipmentArrivalDateFrom:
          type: string
          description: 出荷不可入荷日(FROM)
          format: date-time
          maxLength: 8
        stopShipmentArrivalDateTo:
          type: string
          description: 出荷不可入荷日(TO)
          format: date-time
          maxLength: 8
        globalNumber:
          type: string
          description: グローバル番号
          maxLength: 14
        stopShipmentDateFrom:
          type: string
          description: 出荷不可出荷日(From)
          format: date-time
          maxLength: 8
        stopShipmentDateTo:
          type: string
          description: 出荷不可出荷日(To)
          format: date-time
          maxLength: 8
        customerCode:
          type: string
          description: 得意先コード
          maxLength: 6
        voucherType:
          type: string
          description: 伝区コード
          maxLength: 3
        sendSlipType:
          type: string
          description: 伝票送付区分
          maxLength: 1
        stopShipmentFlag:
          type: string
          description: 出荷不可フラグ
          maxLength: 1
        supplierInvNo:
          type: string
          description: Supplier I/V No
          maxLength: 25
        marketCode:
          type: string
          description: 市場コード
          maxLength: 2
        contactList:
          type: string
          description: 連絡リスト
          maxLength: 1
        registerUserId:
          type: string
          description: 登録者ID
          maxLength: 4
        soStatus:
          type: string
          description: 受注状態
          maxLength: 1
        inquiryTarget:
          type: string
          description: 照会対象区分
          maxLength: 1
        storkCode:
          type: string
          description: ストークコード
          maxLength: 2
        shipmentMeansType:
          type: string
          description: 出荷方法コード
          maxLength: 4
        stockType:
          type: string
          description: 在庫区分
          maxLength: 1
        maxCount:
          description: 参照最大件数
          type: integer
        receptionDate:
          type: string
          description: 受付日時
          format: date-time
      required:
        - stopShipmentArrivalDateFrom
        - stopShipmentDateFrom
        - receptionDate
    DownloadStopShipmentInternalResponseV1:
      title: DownloadStopShipmentInternalResponseV1
      type: object
      properties:
        receptionResult:
          type: string
          description: 受付可否結果
          maxLength: 1
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
      required:
        - receptionResult
    BulkSearchStopShipmentInternalErrorListV1:
      title: BulkSearchStopShipmentInternalErrorListV1
      type: object
      properties:
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
  parameters:
    offset:
      name: offset
      in: query
      required: true
      schema:
        type: integer
      description: 取得開始位置
    limit:
      name: limit
      in: query
      required: true
      schema:
        type: integer
      description: 返却件数
    sortby:
      name: sortby
      in: query
      required: true
      schema:
        type: string
      description: ソート順1
    sortby2:
      name: sortby2
      in: query
      required: true
      schema:
        type: string
      description: ソート順2
tags:
  - name: StopShipmentInternal
